---
# tasks file for ansible-docker  tasks:
# - name: Update apt cache
#   become: true
#   apt:
#     update_cache: yes
- name: Install docker repository dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
- name: Install docker apt key
  become: true
  apt_key:
    id: "{{ docker.apt_key }}"
    url: "{{ docker.key_url }}"
- name: Add docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
- name: Install docker CE
  become: true
  apt:
    name: docker-ce
    state: installed
    update_cache: yes
- name: Create group docker
  become: true
  group:
    name: docker
    state: present
- name: Add {{ ansible_user_id }} to docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
